POST http://localhost:80/api/item
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"

field-value
--WebAppBoundary--

###
### Register a new user
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123",
  "email": "test@example.com",
  "full_name": "Test User"
}

###
### Login with user credentials
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###
### Change Password
POST http://localhost:8000/api/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUzMDU1OTcsImlhdCI6MTc0NTIxOTE5NywidXNlcl9pZCI6NDF9.Io_cS5fYUJN8lxOMlzxlmIvay_1ASkRhRhN1j3-RzVc

{
  "current_password": "password123",
  "new_password": "newpassword123"
}

###
