// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"management-be/internal/repository/ent/matchesgateway"
	"management-be/internal/repository/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MatchesGatewayDelete is the builder for deleting a MatchesGateway entity.
type MatchesGatewayDelete struct {
	config
	hooks    []Hook
	mutation *MatchesGatewayMutation
}

// Where appends a list predicates to the MatchesGatewayDelete builder.
func (mgd *MatchesGatewayDelete) Where(ps ...predicate.MatchesGateway) *MatchesGatewayDelete {
	mgd.mutation.Where(ps...)
	return mgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mgd *MatchesGatewayDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mgd.sqlExec, mgd.mutation, mgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mgd *MatchesGatewayDelete) ExecX(ctx context.Context) int {
	n, err := mgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mgd *MatchesGatewayDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(matchesgateway.Table, sqlgraph.NewFieldSpec(matchesgateway.FieldID, field.TypeInt))
	if ps := mgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mgd.mutation.done = true
	return affected, err
}

// MatchesGatewayDeleteOne is the builder for deleting a single MatchesGateway entity.
type MatchesGatewayDeleteOne struct {
	mgd *MatchesGatewayDelete
}

// Where appends a list predicates to the MatchesGatewayDelete builder.
func (mgdo *MatchesGatewayDeleteOne) Where(ps ...predicate.MatchesGateway) *MatchesGatewayDeleteOne {
	mgdo.mgd.mutation.Where(ps...)
	return mgdo
}

// Exec executes the deletion query.
func (mgdo *MatchesGatewayDeleteOne) Exec(ctx context.Context) error {
	n, err := mgdo.mgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{matchesgateway.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mgdo *MatchesGatewayDeleteOne) ExecX(ctx context.Context) {
	if err := mgdo.Exec(ctx); err != nil {
		panic(err)
	}
}
