// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"management-be/internal/repository/ent/predicate"
	"management-be/internal/repository/ent/teamfee"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamFeeQuery is the builder for querying TeamFee entities.
type TeamFeeQuery struct {
	config
	ctx        *QueryContext
	order      []teamfee.OrderOption
	inters     []Interceptor
	predicates []predicate.TeamFee
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamFeeQuery builder.
func (tfq *TeamFeeQuery) Where(ps ...predicate.TeamFee) *TeamFeeQuery {
	tfq.predicates = append(tfq.predicates, ps...)
	return tfq
}

// Limit the number of records to be returned by this query.
func (tfq *TeamFeeQuery) Limit(limit int) *TeamFeeQuery {
	tfq.ctx.Limit = &limit
	return tfq
}

// Offset to start from.
func (tfq *TeamFeeQuery) Offset(offset int) *TeamFeeQuery {
	tfq.ctx.Offset = &offset
	return tfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tfq *TeamFeeQuery) Unique(unique bool) *TeamFeeQuery {
	tfq.ctx.Unique = &unique
	return tfq
}

// Order specifies how the records should be ordered.
func (tfq *TeamFeeQuery) Order(o ...teamfee.OrderOption) *TeamFeeQuery {
	tfq.order = append(tfq.order, o...)
	return tfq
}

// First returns the first TeamFee entity from the query.
// Returns a *NotFoundError when no TeamFee was found.
func (tfq *TeamFeeQuery) First(ctx context.Context) (*TeamFee, error) {
	nodes, err := tfq.Limit(1).All(setContextOp(ctx, tfq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamfee.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tfq *TeamFeeQuery) FirstX(ctx context.Context) *TeamFee {
	node, err := tfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamFee ID from the query.
// Returns a *NotFoundError when no TeamFee ID was found.
func (tfq *TeamFeeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tfq.Limit(1).IDs(setContextOp(ctx, tfq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamfee.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tfq *TeamFeeQuery) FirstIDX(ctx context.Context) int {
	id, err := tfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamFee entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamFee entity is found.
// Returns a *NotFoundError when no TeamFee entities are found.
func (tfq *TeamFeeQuery) Only(ctx context.Context) (*TeamFee, error) {
	nodes, err := tfq.Limit(2).All(setContextOp(ctx, tfq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamfee.Label}
	default:
		return nil, &NotSingularError{teamfee.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tfq *TeamFeeQuery) OnlyX(ctx context.Context) *TeamFee {
	node, err := tfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamFee ID in the query.
// Returns a *NotSingularError when more than one TeamFee ID is found.
// Returns a *NotFoundError when no entities are found.
func (tfq *TeamFeeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tfq.Limit(2).IDs(setContextOp(ctx, tfq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamfee.Label}
	default:
		err = &NotSingularError{teamfee.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tfq *TeamFeeQuery) OnlyIDX(ctx context.Context) int {
	id, err := tfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamFees.
func (tfq *TeamFeeQuery) All(ctx context.Context) ([]*TeamFee, error) {
	ctx = setContextOp(ctx, tfq.ctx, ent.OpQueryAll)
	if err := tfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamFee, *TeamFeeQuery]()
	return withInterceptors[[]*TeamFee](ctx, tfq, qr, tfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tfq *TeamFeeQuery) AllX(ctx context.Context) []*TeamFee {
	nodes, err := tfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamFee IDs.
func (tfq *TeamFeeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tfq.ctx.Unique == nil && tfq.path != nil {
		tfq.Unique(true)
	}
	ctx = setContextOp(ctx, tfq.ctx, ent.OpQueryIDs)
	if err = tfq.Select(teamfee.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tfq *TeamFeeQuery) IDsX(ctx context.Context) []int {
	ids, err := tfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tfq *TeamFeeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tfq.ctx, ent.OpQueryCount)
	if err := tfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tfq, querierCount[*TeamFeeQuery](), tfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tfq *TeamFeeQuery) CountX(ctx context.Context) int {
	count, err := tfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tfq *TeamFeeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tfq.ctx, ent.OpQueryExist)
	switch _, err := tfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tfq *TeamFeeQuery) ExistX(ctx context.Context) bool {
	exist, err := tfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamFeeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tfq *TeamFeeQuery) Clone() *TeamFeeQuery {
	if tfq == nil {
		return nil
	}
	return &TeamFeeQuery{
		config:     tfq.config,
		ctx:        tfq.ctx.Clone(),
		order:      append([]teamfee.OrderOption{}, tfq.order...),
		inters:     append([]Interceptor{}, tfq.inters...),
		predicates: append([]predicate.TeamFee{}, tfq.predicates...),
		// clone intermediate query.
		sql:  tfq.sql.Clone(),
		path: tfq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Amount float64 `json:"amount,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamFee.Query().
//		GroupBy(teamfee.FieldAmount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tfq *TeamFeeQuery) GroupBy(field string, fields ...string) *TeamFeeGroupBy {
	tfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamFeeGroupBy{build: tfq}
	grbuild.flds = &tfq.ctx.Fields
	grbuild.label = teamfee.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Amount float64 `json:"amount,omitempty"`
//	}
//
//	client.TeamFee.Query().
//		Select(teamfee.FieldAmount).
//		Scan(ctx, &v)
func (tfq *TeamFeeQuery) Select(fields ...string) *TeamFeeSelect {
	tfq.ctx.Fields = append(tfq.ctx.Fields, fields...)
	sbuild := &TeamFeeSelect{TeamFeeQuery: tfq}
	sbuild.label = teamfee.Label
	sbuild.flds, sbuild.scan = &tfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamFeeSelect configured with the given aggregations.
func (tfq *TeamFeeQuery) Aggregate(fns ...AggregateFunc) *TeamFeeSelect {
	return tfq.Select().Aggregate(fns...)
}

func (tfq *TeamFeeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tfq); err != nil {
				return err
			}
		}
	}
	for _, f := range tfq.ctx.Fields {
		if !teamfee.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tfq.path != nil {
		prev, err := tfq.path(ctx)
		if err != nil {
			return err
		}
		tfq.sql = prev
	}
	return nil
}

func (tfq *TeamFeeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamFee, error) {
	var (
		nodes = []*TeamFee{}
		_spec = tfq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamFee).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamFee{config: tfq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tfq *TeamFeeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tfq.querySpec()
	_spec.Node.Columns = tfq.ctx.Fields
	if len(tfq.ctx.Fields) > 0 {
		_spec.Unique = tfq.ctx.Unique != nil && *tfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tfq.driver, _spec)
}

func (tfq *TeamFeeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teamfee.Table, teamfee.Columns, sqlgraph.NewFieldSpec(teamfee.FieldID, field.TypeInt))
	_spec.From = tfq.sql
	if unique := tfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tfq.path != nil {
		_spec.Unique = true
	}
	if fields := tfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamfee.FieldID)
		for i := range fields {
			if fields[i] != teamfee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tfq *TeamFeeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tfq.driver.Dialect())
	t1 := builder.Table(teamfee.Table)
	columns := tfq.ctx.Fields
	if len(columns) == 0 {
		columns = teamfee.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tfq.sql != nil {
		selector = tfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tfq.ctx.Unique != nil && *tfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tfq.predicates {
		p(selector)
	}
	for _, p := range tfq.order {
		p(selector)
	}
	if offset := tfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TeamFeeGroupBy is the group-by builder for TeamFee entities.
type TeamFeeGroupBy struct {
	selector
	build *TeamFeeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tfgb *TeamFeeGroupBy) Aggregate(fns ...AggregateFunc) *TeamFeeGroupBy {
	tfgb.fns = append(tfgb.fns, fns...)
	return tfgb
}

// Scan applies the selector query and scans the result into the given value.
func (tfgb *TeamFeeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tfgb.build.ctx, ent.OpQueryGroupBy)
	if err := tfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamFeeQuery, *TeamFeeGroupBy](ctx, tfgb.build, tfgb, tfgb.build.inters, v)
}

func (tfgb *TeamFeeGroupBy) sqlScan(ctx context.Context, root *TeamFeeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tfgb.fns))
	for _, fn := range tfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tfgb.flds)+len(tfgb.fns))
		for _, f := range *tfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamFeeSelect is the builder for selecting fields of TeamFee entities.
type TeamFeeSelect struct {
	*TeamFeeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tfs *TeamFeeSelect) Aggregate(fns ...AggregateFunc) *TeamFeeSelect {
	tfs.fns = append(tfs.fns, fns...)
	return tfs
}

// Scan applies the selector query and scans the result into the given value.
func (tfs *TeamFeeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tfs.ctx, ent.OpQuerySelect)
	if err := tfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamFeeQuery, *TeamFeeSelect](ctx, tfs.TeamFeeQuery, tfs, tfs.inters, v)
}

func (tfs *TeamFeeSelect) sqlScan(ctx context.Context, root *TeamFeeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tfs.fns))
	for _, fn := range tfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
