CREATE TABLE matches_gateway
(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "competition_name"     TEXT                      NOT NULL,
    "season_start_date"    DATE                      NOT NULL,
    "match_date"           TIMESTAMP WITH TIME ZONE  NOT NULL,
    "home_team_name"       TEXT                      NOT NULL,
    "home_team_short_name" TEXT                      NOT NULL,
    "home_team_logo"       TEXT                      NOT NULL,
    "away_team_name"       TEXT                      NOT NULL,
    "away_team_short_name" TEXT                      NOT NULL,
    "away_team_logo"       TEXT                      NOT NULL,
    "home_score"           INTEGER,
    "away_score"           INTEGER,
    "status"               TEXT                      NOT NULL DEFAULT 'scheduled',
    "created_at"           TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),
    "updated_at"           TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT NOW(),
    "deleted_at"           TIMESTAMP WITH TIME ZONE
);
