CREATE TABLE IF NOT EXISTS "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL CONSTRAINT "username_check" CHECK ("username" <> ''::TEXT),
    "password" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "full_name" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE IF NOT EXISTS "departments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL CONSTRAINT "name_check" CHECK ("name" <> ''::TEXT),
    "description" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE IF NOT EXISTS "players" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "department_id" BIGINT NOT NULL,
    "full_name" TEXT NOT NULL CONSTRAINT "full_name_check" CHECK ("full_name" <> ''::TEXT),
    "jersey_number" INTEGER UNIQUE,
    "position" TEXT NOT NULL,
    "date_of_birth" DATE,
    "height_cm" INTEGER,
    "weight_kg" INTEGER,
    "phone" TEXT DEFAULT '',
    "email" TEXT DEFAULT '',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL,
    FOREIGN KEY ("department_id") REFERENCES "departments" ("id")
);

CREATE TABLE IF NOT EXISTS "teams" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL CONSTRAINT "team_name_check" CHECK ("name" <> ''::TEXT),
    "company_name" TEXT DEFAULT '',
    "contact_person" TEXT DEFAULT '',
    "contact_phone" TEXT DEFAULT '',
    "contact_email" TEXT DEFAULT '',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE IF NOT EXISTS "matches" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "opponent_team_id" BIGINT NOT NULL,
    "match_date" TIMESTAMP WITH TIME ZONE NOT NULL,
    "venue" TEXT DEFAULT '',
    "is_home_game" BOOLEAN NOT NULL DEFAULT true,
    "our_score" INTEGER,
    "opponent_score" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "notes" TEXT DEFAULT '',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL,
    FOREIGN KEY ("opponent_team_id") REFERENCES "teams" ("id")
);

CREATE TABLE IF NOT EXISTS "match_players" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "match_id" BIGINT NOT NULL,
    "player_id" BIGINT NOT NULL,
    "minutes_played" INTEGER NOT NULL DEFAULT 0,
    "goals_scored" INTEGER NOT NULL DEFAULT 0,
    "assists" INTEGER NOT NULL DEFAULT 0,
    "yellow_cards" INTEGER NOT NULL DEFAULT 0,
    "red_card" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL,
    UNIQUE("match_id", "player_id"),
    FOREIGN KEY ("match_id") REFERENCES "matches" ("id"),
    FOREIGN KEY ("player_id") REFERENCES "players" ("id")
);

CREATE TABLE IF NOT EXISTS "team_fees" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "amount" DECIMAL(10,2) NOT NULL,
    "payment_date" DATE NOT NULL,
    "description" TEXT DEFAULT '',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE IF NOT EXISTS "player_statistics" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "player_id" BIGINT NOT NULL,
    "total_matches" INTEGER NOT NULL DEFAULT 0,
    "total_minutes_played" INTEGER NOT NULL DEFAULT 0,
    "total_goals" INTEGER NOT NULL DEFAULT 0,
    "total_assists" INTEGER NOT NULL DEFAULT 0,
    "total_yellow_cards" INTEGER NOT NULL DEFAULT 0,
    "total_red_cards" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "deleted_at" TIMESTAMP WITH TIME ZONE NULL,
    UNIQUE("player_id"),
    FOREIGN KEY ("player_id") REFERENCES "players" ("id")
);