// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Department struct {
	ent.Schema
}

func (Department) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("name"), field.String("description"), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional()}
}
func (Department) Edges() []ent.Edge {
	return []ent.Edge{edge.To("players", Player.Type)}
}
func (Department) Annotations() []schema.Annotation {
	return nil
}
