// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type MatchesGateway struct {
	ent.Schema
}

func (MatchesGateway) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.String("competition_name"), field.Time("season_start_date"), field.Time("match_date"), field.String("home_team_name"), field.String("home_team_short_name"), field.String("home_team_logo"), field.String("away_team_name"), field.String("away_team_short_name"), field.String("away_team_logo"), field.Int32("home_score").Optional(), field.Int32("away_score").Optional(), field.String("status"), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional()}
}
func (MatchesGateway) Edges() []ent.Edge {
	return nil
}
func (MatchesGateway) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "matches_gateway"}}
}
