// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type MatchPlayer struct {
	ent.Schema
}

func (MatchPlayer) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("match_id").Optional(), field.Int("player_id").Optional(), field.Int32("minutes_played"), field.Int32("goals_scored"), field.Int32("assists"), field.Int32("yellow_cards"), field.Bool("red_card"), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional()}
}
func (MatchPlayer) Edges() []ent.Edge {
	return []ent.Edge{edge.From("match", Match.Type).Ref("match_players").Unique().Field("match_id"), edge.From("player", Player.Type).Ref("match_players").Unique().Field("player_id")}
}
func (MatchPlayer) Annotations() []schema.Annotation {
	return nil
}
