// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Match struct {
	ent.Schema
}

func (Match) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.Int32("opponent_team_id").Optional(), field.Time("match_date"), field.String("venue").Optional(), field.Bool("is_home_game").Optional(), field.Int32("our_score").Optional(), field.Int32("opponent_score").Optional(), field.String("status").Optional(), field.String("notes").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (Match) Edges() []ent.Edge {
	return []ent.Edge{edge.To("match_players", MatchPlayer.Type), edge.From("team", Team.Type).Ref("matches").Unique().Field("opponent_team_id")}
}
func (Match) Annotations() []schema.Annotation {
	return nil
}
