// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type PlayerStatistic struct {
	ent.Schema
}

func (PlayerStatistic) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("player_id").Optional().Unique(), field.Int32("total_matches"), field.Int32("total_minutes_played"), field.Int32("total_goals"), field.Int32("total_assists"), field.Int32("total_yellow_cards"), field.Int32("total_red_cards"), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional()}
}
func (PlayerStatistic) Edges() []ent.Edge {
	return []ent.Edge{edge.From("player", Player.Type).Ref("player_statistic").Unique().Field("player_id")}
}
func (PlayerStatistic) Annotations() []schema.Annotation {
	return nil
}
