// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type TeamFee struct {
	ent.Schema
}

func (TeamFee) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Float("amount"), field.Time("payment_date"), field.String("description").Optional(), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional()}
}
func (TeamFee) Edges() []ent.Edge {
	return nil
}
func (TeamFee) Annotations() []schema.Annotation {
	return nil
}
