// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Match is the predicate function for match builders.
type Match func(*sql.Selector)

// MatchPlayer is the predicate function for matchplayer builders.
type MatchPlayer func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// PlayerStatistic is the predicate function for playerstatistic builders.
type PlayerStatistic func(*sql.Selector)

// SchemaMigration is the predicate function for schemamigration builders.
type SchemaMigration func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// TeamFee is the predicate function for teamfee builders.
type TeamFee func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
